### ISSUE TITLE
目錄指向錯誤&目錄畫面跳開回不去了

### ISSUE THREAD

**Issue by padmatara** [karmapa/adarsha2014#104]
![prob 1126-1](https://cloud.githubusercontent.com/assets/8554534/5200448/167fa590-75a1-11e4-90c3-3117b112fb32.png)
![prob 1126-2](https://cloud.githubusercontent.com/assets/8554534/5200446/167b4b08-75a1-11e4-82f7-8f40c76402b0.png)
![prob 1126-3](https://cloud.githubusercontent.com/assets/8554534/5200447/167c910c-75a1-11e4-8e59-d044c1568d7a.png)
![prob 1126-4](https://cloud.githubusercontent.com/assets/8554534/5200451/168251aa-75a1-11e4-81ab-f9db84184952.png)
![prob 1126-5](https://cloud.githubusercontent.com/assets/8554534/5200449/167fc70a-75a1-11e4-9d64-8242f20c6c12.png)
![prob 1126-6](https://cloud.githubusercontent.com/assets/8554534/5200450/16800152-75a1-11e4-9f50-a7ff547bd422.png)
![prob 1126-7](https://cloud.githubusercontent.com/assets/8554534/5200452/169d5af4-75a1-11e4-9b12-83608b557969.png)
![prob 1126-8](https://cloud.githubusercontent.com/assets/8554534/5200454/16a3b7f0-75a1-11e4-8b88-646426bc6440.png)
![prob 1126-9](https://cloud.githubusercontent.com/assets/8554534/5200455/16a6f0e6-75a1-11e4-9a76-e5e5d4d321b5.png)
![prob 1126-10](https://cloud.githubusercontent.com/assets/8554534/5200453/16a29712-75a1-11e4-99d9-9e2444dc572f.png)
![prob 1126-11](https://cloud.githubusercontent.com/assets/8554534/5200458/16c49790-75a1-11e4-8b0b-e3815a1544fc.png)
![prob 1126-12](https://cloud.githubusercontent.com/assets/8554534/5200456/16aa0448-75a1-11e4-83ec-197c2a54955c.png)
![prob 1126-13](https://cloud.githubusercontent.com/assets/8554534/5200457/16c3b5be-75a1-11e4-97e5-31a569917ea5.png)
![prob 1126-14](https://cloud.githubusercontent.com/assets/8554534/5200459/16c552ca-75a1-11e4-997a-7945c38e53f8.png)
![prob 1126-15](https://cloud.githubusercontent.com/assets/8554534/5200460/16cc251e-75a1-11e4-99c6-224626f1f619.png)
![prob 1126-16](https://cloud.githubusercontent.com/assets/8554534/5200462/16cdfd94-75a1-11e4-8619-a99fe885c0e2.png)
![prob 1126-17](https://cloud.githubusercontent.com/assets/8554534/5200461/16cdf3c6-75a1-11e4-92ac-390a6f2319b0.png)
○○ＡＣ○○○

**Comment by ahsyuyu** [comment]
9.169a該目錄的起始應該是9.170a，因為頁面已經卷到最底所以才無法精準指到
9.212a, 9.250a因為頁面已經卷到最底所以才無法精準指到

其他的目錄都有對上了

**Comment by padmatara** [comment]
OK, no prob!

_May you be well. May you be happy. ~Annie~_

ahsyuyu notifications@github.com 於 2014年11月27日 下午2:09 寫道：

**Comment by lamalien** [comment]
已修正
