### ISSUE TITLE
出現當機畫面

### ISSUE THREAD

**Issue by shu-hui** [karmapa/adarsha2014#120]
![default](https://cloud.githubusercontent.com/assets/7776378/5214418/db31e316-7656-11e4-8942-ff722297a04d.png)

**Comment by shu-hui** [comment]
འཕགས་པ་གསེར་འོད་དམ་པ་མདོ་སྡེའི་དབང་པོའི་རྒྱལ་པོ་ལས་གསུངས་པའི་སྨོན་ལམ།

**Comment by shu-hui** [comment]
p.s  此函(13) 幾乎都有此問題, 點圖會出現當機畫面

**Comment by ahsyuyu** [comment]
謝謝回報～因為對應的K經號有點問題，目前已先拿掉有問題的對照，程式也不會突然跳到當掉的畫面了～

**Comment by lamalien** [comment]
已修正
