### ISSUE TITLE
經文沒有出現

### ISSUE THREAD

**Issue by padmatara** [karmapa/adarsha2014#121]
![prob1128-1](https://cloud.githubusercontent.com/assets/8554534/5223443/e71dd0f2-76f3-11e4-90dc-1aa3132799a2.png)

**Comment by ahsyuyu** [comment]
回去看原始文檔該頁沒有內容，法海師表示有待查證～

**Comment by lamalien** [comment]
69.148a & 69.148b 所顯示圖檔一樣
69.148a應該是空白頁
暫時不用修改
以後要把69.148a換成空白頁

，
