### ISSUE TITLE
問題 : 目錄顯示錯誤

### ISSUE THREAD

**Issue by shu-hui** [karmapa/adarsha2014#14]
![-1](https://cloud.githubusercontent.com/assets/7776378/4673533/296e6c44-55a4-11e4-9a91-25534074a126.png)
![-2](https://cloud.githubusercontent.com/assets/7776378/4673535/2d9ee8b6-55a4-11e4-9ee6-af91657da7da.png)

**Comment by ahsyuyu** [comment]
以下是長度大於三倍平均值，經由確認原始資料，程式沒有抓head裡的t或者tag包起內容的head：
file 308 012/lj0008_014.xml page 15
file 1033 046/lj0060_001.xml page 1
file 1181 052/lj0086_001.xml page 2
file 1185 052/lj0089_001.xml page 1
file 1201 052/lj0092_001.xml page 1
file 1223 053/lj0099_001.xml page 1
file 1224 053/lj0100_001.xml page 1
file 1252 054/lj0112_001.xml page 1
file 1282 055/lj0123_001.xml page 1
file 1306 056/lj0135_001.xml page 1

**Comment by shu-hui** [comment]
![-3](https://cloud.githubusercontent.com/assets/7776378/4677105/25651ba4-55e3-11e4-8d76-a15b8c390fa3.png)
![-4](https://cloud.githubusercontent.com/assets/7776378/4677107/2a436bf8-55e3-11e4-9a0e-a2e626069f0c.png)
![-5](https://cloud.githubusercontent.com/assets/7776378/4677109/2db8f3fc-55e3-11e4-83ac-dd6f94003e00.png)
