### ISSUE TITLE
Redundant span class="tofind"

### ISSUE THREAD

**Issue by yapcheahshen** [karmapa/adarsha2014#16]
＜span class="tofind"＞ is not needed , use ＜hl＞ return from kse.search.
in css

hl {color:red}
hl[n="1"] {color:blue}  // color of second keyword
hl[n="2"] {color:green}  // color of third keyword

![redundant](https://cloud.githubusercontent.com/assets/1085366/4675197/5f7aba70-560a-11e4-916f-82279e7d07ac.png)

**Comment by ahsyuyu** [comment]
＜hl＞ has been used now. Thank you!
