### ISSUE TITLE
請補上「目錄欄位」部分藏文字句後直線  和  增加「經文閱讀欄位」行距

### ISSUE THREAD

**Issue by khenpo-tengye** [karmapa/adarsha2014#19]
![v1_0_01-pncdemo](https://cloud.githubusercontent.com/assets/5229877/4696073/eea0a9da-5849-11e4-96a8-3ea7cddf593e.png)

**Comment by ahsyuyu** [comment]
1. 發現有非常多的地方都少直線，所以還要討論是不是要用程式去加。
2. 行距的部分已經增加，請看看需不需要再增寬或縮短
   謝謝～

**Comment by khenpo-tengye** [comment]
謝謝，行距這樣感覺不錯。直線部分麻煩淑惠記得一下，看如何處理了。
