### ISSUE TITLE
「搜尋欄位」全選文字後按刪除鍵時會lag幾秒

### ISSUE THREAD

**Issue by khenpo-tengye** [karmapa/adarsha2014#20]
![01](https://cloud.githubusercontent.com/assets/5229877/4696126/8a88caca-584b-11e4-8bb7-65f4b821751a.png)
![02](https://cloud.githubusercontent.com/assets/5229877/4696127/8aadeddc-584b-11e4-9dc8-cf48132e17e2.png)
![03](https://cloud.githubusercontent.com/assets/5229877/4696128/8acbeabc-584b-11e4-8973-6bcaba22913a.png)

**Comment by ahsyuyu** [comment]
清空title search的input（也就是當輸入欄是空的）的時候，不會出現目錄總表了，所以就不會有lag的情況了～Thank you for the feedback! 
若確認沒有問題，再麻煩close這個issue囉！謝謝～
