### ISSUE TITLE
藏文經典標題符號錯誤

### ISSUE THREAD

**Issue by khenpo-tengye** [karmapa/adarsha2014#21]
![v1_0_01-pncdemo](https://cloud.githubusercontent.com/assets/5229877/4696284/af01dca8-584f-11e4-9be3-37ce3a4cb41e.png)

**Comment by ahsyuyu** [comment]
我回去看資料，堪佈所發現的錯誤（雲後面應該要有兩條直線）是原始資料的關係，再麻煩資料組修改藏文經名兩條直線的部分。謝謝～

**Comment by khenpo-tengye** [comment]
麻煩資料組處理了。

**Comment by shu-hui** [comment]
已跟堪布確認過維持目前的雲符符號, 不需修訂為兩條直線.
