### ISSUE TITLE
藏經目錄欄位點選ཁྲིད་པ།，右方不會出現經名，而是直接出現內文

### ISSUE THREAD

**Issue by khenpo-tengye** [karmapa/adarsha2014#22]
![v1_0_01-pncdemo](https://cloud.githubusercontent.com/assets/5229877/4696310/3e017db4-5850-11e4-914d-d3f1f19c2de5.png)

**Comment by ahsyuyu** [comment]
回去看資料發現37.1a是空的，所以程式才會直接抓37.1b的內文，已經請資料組找經名了，等資料組找到會再補上。Thank you for the feedback!

**Comment by lamalien** [comment]
已修正
