### ISSUE TITLE
問題:藏文錯誤

### ISSUE THREAD

**Issue by shu-hui** [karmapa/adarsha2014#25]
![default](https://cloud.githubusercontent.com/assets/7776378/4698731/02f06c48-5838-11e4-9a6c-161dd9caac01.png)
![-1](https://cloud.githubusercontent.com/assets/7776378/4698730/02ec3de4-5838-11e4-8beb-8e11623dd10a.png)

**Comment by ahsyuyu** [comment]
資料庫已經更新，錯誤的字已更正，確認沒問題再麻煩close這個issue囉！謝謝

**Comment by shu-hui** [comment]
已修訂ok. 謝謝 !!
