### ISSUE TITLE
問題:目錄的多與少

### ISSUE THREAD

**Issue by shu-hui** [karmapa/adarsha2014#28]
![default](https://cloud.githubusercontent.com/assets/7776378/4715945/a76a30a8-5903-11e4-83d0-cc7e0831e372.png)

**Comment by ahsyuyu** [comment]
可以給我少的那個字的文字嗎～我再用copy paste找為什麼為少顯示這個
因為這些bampo是有連續的，想問一下多出來的是應該要在別的目錄底下，但跑來這裡嗎？

**Comment by shu-hui** [comment]
Dear 香毓：

下午再給妳喔

請等等

```
        淑惠 ＾＿＾
```

ahsyuyu notifications@github.com 於 2014年10月23日 上午10:39 寫道：
