### ISSUE TITLE
目錄列：Jiang Kangyur 文字置換～

### ISSUE THREAD

**Issue by khenpo-tengye** [karmapa/adarsha2014#32]
法王指示以下文字請替換成藏文，謝謝。

འཇང་བཀའ་འགྱུར།

![v0_0_28-adarsha](https://cloud.githubusercontent.com/assets/5229877/4806019/6b5d9088-5e84-11e4-9864-12c1de0043b6.png)

**Comment by ahsyuyu** [comment]
已經改好囉，謝謝～
