### ISSUE TITLE
目錄列：目錄列和右邊閱讀視窗間，請加一條細線

### ISSUE THREAD

**Issue by khenpo-tengye** [karmapa/adarsha2014#33]
法王提到，請加上一條細線區隔～
![2014-10-28 2 56 09](https://cloud.githubusercontent.com/assets/5229877/4806126/084105a0-5e86-11e4-9da7-57b23f28e86d.png)

**Comment by g1ahsia** [comment]
感謝法王與堪布的建議。真不錯，香毓做的越來越像原本設計的mockup了。

我的建議如下（請見下圖）：
1. 左上角可加一個logo，以增加產品識別度。
2. 中間可以加一條淡淡的淺灰色線條以區別清單和內文。
3. 上下頁的按鈕可以做的小一點點，已不妨礙閱讀為原則。請Rita提供設計好的左右按鈕。
4. \+ - 號請用設計好的icon圖檔而不是用文字的+ -
5. Catelog, Title Search, Text Search 是否也要換成藏文呢？
6. 右上角的語言選項，看來不來得及在這一版做好，以切換藏文，英文和中文，若來不及就放到下一版。

謝謝 & 加油

Allen

**Comment by khenpo-tengye** [comment]
Allen, 

謝謝！第六點，法王也有提到，謝謝提醒。我拿到正確藏文的話儘快再給各位。

現在畫面愈來愈漂亮了。

堪布
