### ISSUE TITLE
單機版（Mac版）：藏文字體和網路版不同、圖示按鈕遺漏等問題

### ISSUE THREAD

**Issue by khenpo-tengye** [karmapa/adarsha2014#35]
如圖。
![v0_0_31-adarsha](https://cloud.githubusercontent.com/assets/5229877/4878532/e2b66e7c-630f-11e4-86f6-ede03a75807b.png)
![v0_1_03-adarsha](https://cloud.githubusercontent.com/assets/5229877/4878531/e2b30372-630f-11e4-814d-5bde5d1e6c1f.png)

**Comment by khenpo-tengye** [comment]
香毓，麻煩用這個字體：

http://www.tibetanfont.org/himalaya.html

**Comment by ahsyuyu** [comment]
謝謝堪布～
裡面有兩種，一種是一般，一種是可以跟英文並排的bigger版，請問要哪一種呢～

Best,

香毓

Khenpo Lodro Tengye notifications@github.com 於 2014/11/3 下午4:26 寫道：

**Comment by g1ahsia** [comment]
Online font converters: 

http://everythingfonts.com/ttf-to-woff http://everythingfonts.com/ttf-to-woff
http://convertfonts.com http://convertfonts.com/

FYI

Allen

**Comment by khenpo-tengye** [comment]
香毓，
是哪兩種我也不清楚喔～如果和英文能配合的，頁面的呈現上，可能比較好看。還是請妳都試試看。
堪布

**Comment by khenpo-tengye** [comment]
提醒一下：
1. 寶藏學會的Logo，也請換成藏英文都有的那個。
2. ADARSHA變形～要請馨儀調整一下喔。
堪布
