### ISSUE TITLE
「閱讀頁面」上滑鼠會呈現「點選狀態」～

### ISSUE THREAD

**Issue by khenpo-tengye** [karmapa/adarsha2014#37]
以蘋果電腦來說，平時滑鼠是箭頭，但滑到可以點選的Link上時，會變成一隻手掌。

發現更新後，滑鼠只要移到右邊閱讀頁面上，無論任何地方，都呈現點選狀態的手掌。

應該有問題～

堪布

**Comment by ahsyuyu** [comment]
謝謝提供～
已經修正好了
再請堪布看看還有沒有問題喔！
