### ISSUE TITLE
單機版（PC版）：目錄顯示錯誤

### ISSUE THREAD

**Issue by shu-hui** [karmapa/adarsha2014#39]
![3](https://cloud.githubusercontent.com/assets/7776378/4971364/dd7ee9be-68d9-11e4-90ff-ae32136d09e2.png)
![4](https://cloud.githubusercontent.com/assets/7776378/4971365/dd7ffb2e-68d9-11e4-9197-9224bcf01575.png)

![2](https://cloud.githubusercontent.com/assets/7776378/4970800/8d9ba7e2-688a-11e4-8b68-0c580fe85841.png)
![1](https://cloud.githubusercontent.com/assets/7776378/4970693/1654e8da-6888-11e4-9663-94c082878dbd.png)

**Comment by ahsyuyu** [comment]
第1,2,4張圖的問題已經解決，第3張要回到原始檔案改～

**Comment by shu-hui** [comment]
第3張要回到原始檔案改～的意思是？
ｘｍｌ裡面沒有錯誤喔
