### ISSUE TITLE
問題：Title搜尋欄位

### ISSUE THREAD

**Issue by khenpo-tengye** [karmapa/adarsha2014#4]
![_2014_10_14_ 8_48](https://cloud.githubusercontent.com/assets/5229877/4622459/6936b1de-533c-11e4-8cd4-f59170e29fff.png)

**Comment by ahsyuyu** [comment]
1: 因為程式設定只要輸入欄有變化會同步更新搜尋結果，所以當把內容都清掉會出現總目錄列表。可以再依使用者習慣考慮要將預設值byang chub拿掉或者是輸入欄全清空時隱藏這個總目錄
2: 問題解決中，問題解決的新版本release後會在此回覆
Thank you for the advises!

**Comment by khenpo-tengye** [comment]
了解，謝謝～

**Comment by lamalien** [comment]
已修正
