### ISSUE TITLE
單機版（PC版）：ADARSHA 搜尋功能 : 目錄搜尋的頁面下目錄顯示不完整或錯誤

### ISSUE THREAD

**Issue by shu-hui** [karmapa/adarsha2014#41]
![6-3](https://cloud.githubusercontent.com/assets/7776378/4971992/878387b4-68e7-11e4-8538-f2781aead120.png)
![6-1](https://cloud.githubusercontent.com/assets/7776378/4971946/e42a7a82-68e6-11e4-8af4-c5d7c32d92ad.png)
![6-2](https://cloud.githubusercontent.com/assets/7776378/4971947/e42b02ea-68e6-11e4-935d-a635663e9ac8.png)

**Comment by ahsyuyu** [comment]
謝謝淑費姊姊提供
可以麻煩提供搜尋哪些關鍵字會出現目錄顯示不完整的畫面嗎
Thank you~

**Comment by shu-hui** [comment]
好的! 整理後給妳~
謝謝 ^_^

**Comment by shu-hui** [comment]
香毓:

先提供其中漏字的部分
發現在vol.039均為首字未顯示

![11](https://cloud.githubusercontent.com/assets/7776378/4988286/0eeb047a-699c-11e4-8008-5248d6d9bc9b.png)
![11-1](https://cloud.githubusercontent.com/assets/7776378/4988287/0f1092ee-699c-11e4-8d37-2fb549a81353.png)

**Comment by shu-hui** [comment]
香毓:

這是在搜尋功能頁面，搜尋欄"空白"的時候呈現的畫面

下面在整理了一些程式的問題(紅圈處)

後面紅字為資料的部分已修改!

![12](https://cloud.githubusercontent.com/assets/7776378/4989491/7c740d80-69b4-11e4-84eb-d97c6be9fa65.png)
