### ISSUE TITLE
ADARSHA 搜尋功能 : 目錄搜尋在右側頁面顯示不明字體

### ISSUE THREAD

**Issue by shu-hui** [karmapa/adarsha2014#42]
![7](https://cloud.githubusercontent.com/assets/7776378/4972111/be4fe70c-68a5-11e4-96b8-8ee4c334e9e7.png)
![7-1](https://cloud.githubusercontent.com/assets/7776378/4972112/be56d9a4-68a5-11e4-9ca1-ea070fab5947.png)

**Comment by ahsyuyu** [comment]
這個bug在最新版已經解決了～
試著重複同樣的操作步驟於網頁：http://karmapa.github.io/adarsha/
看問題還在不在～如果還是有問題再麻煩跟我說怎麼操作會出現<hl>了
謝謝！

**Comment by shu-hui** [comment]
嗯! 現在操作沒有出現了
謝謝 ^_^
