### ISSUE TITLE
單機版（PC版）：ADARSHA 搜尋功能 : 出現bug

### ISSUE THREAD

**Issue by shu-hui** [karmapa/adarsha2014#46]
![bug](https://cloud.githubusercontent.com/assets/7776378/5025942/7f9a9992-6b59-11e4-9ccd-13b7e72856b8.png)
![bug2](https://cloud.githubusercontent.com/assets/7776378/5025946/8a0ae8a0-6b59-11e4-8a31-aee6c6521895.png)
![bug3 bug2](https://cloud.githubusercontent.com/assets/7776378/5025949/8e6cd32c-6b59-11e4-9543-00df4a199d6f.png)

**Comment by liangwenwang** [comment]
此issue 已解決. ^~^

**Comment by ahsyuyu** [comment]
謝謝淑費姊姊的回報～問題已解決～
