### ISSUE TITLE
Not correct expand from Kacha to text

### ISSUE THREAD

**Issue by lamalien** [karmapa/adarsha2014#5]
![adarsha issue1014-1](https://cloud.githubusercontent.com/assets/5266492/4623343/260918ba-534c-11e4-9a4d-633b4a2688d7.jpg)

**Comment by ahsyuyu** [comment]
The bug has been fixed. Please see: http://karmapa.github.io/adarsha/
Please close this issue after you confirm this problem is no longer exist. 
Thank you!

**Comment by lamalien** [comment]
已修正
