### ISSUE TITLE
單機版（PC版）：沒有目錄 again~ 與出現不該出現的標記

### ISSUE THREAD

**Issue by shu-hui** [karmapa/adarsha2014#52]
![4](https://cloud.githubusercontent.com/assets/7776378/5086873/6a46a8c2-6f5c-11e4-9696-8d5524ae95ca.png)
![4-1](https://cloud.githubusercontent.com/assets/7776378/5086874/6a497386-6f5c-11e4-973d-83502df8df9d.png)
![4-2](https://cloud.githubusercontent.com/assets/7776378/5086875/6a4dcca6-6f5c-11e4-83f5-ea7ed4dc21d4.png)

**Comment by lamalien** [comment]
vol.033/lj0010_060.xml缺少head 1 &head 2
已經補上

ཆོས་ཀྱི་རྒྱ་མཚོ།

2014-11-18 19:52 GMT+08:00 shu-hui notifications@github.com:

**Comment by lamalien** [comment]
vol.036/lj0011_045缺少head 1 &head 2
已經補上
