### ISSUE TITLE
མདོ་སྡོ། ༼ཁ༽目錄有漏

### ISSUE THREAD

**Issue by shu-hui** [karmapa/adarsha2014#56]
![2](https://cloud.githubusercontent.com/assets/7776378/5122500/66a424c0-70dc-11e4-8778-83d8dfe28222.png)

**Comment by shu-hui** [comment]
目錄有漏, 文檔已修訂, 待系統更新, 謝謝 !!

**Comment by ahsyuyu** [comment]
已經更新資料庫～若沒問題再麻煩close此issue了～謝謝！
