### ISSUE TITLE
མདོ་སྡོ། 目錄最後兩個有多出

### ISSUE THREAD

**Issue by shu-hui** [karmapa/adarsha2014#57]
![1](https://cloud.githubusercontent.com/assets/7776378/5137207/e86ec616-716f-11e4-9b56-290052bf123e.png)

**Comment by lamalien** [comment]
這兩個不是多出來的
70.1a༼ཨཾ༽ ༄༅། ༈མདོ་སྡེ་སྣ་ཚོགས་ཀྱི་སྐོར་བཞུགས་སོ། ། (黃) 經藏第三十一部
71.1a༼ཨཿ༽ ༄༅། ༈མདོ་སྡེ་སྣ་ཚོགས་ཀྱི་སྐོར་བཞུགས་སོ། ། (黃) 經藏第三十二部

**Comment by lamalien** [comment]
མདོ་སྡེ། 最後一函 vol.071目錄顯示應該是
ཨཿ 
![32](https://cloud.githubusercontent.com/assets/5266492/5137532/733f115a-7176-11e4-880a-248ce3cc924c.jpg)
不是  ཿ
