### ISSUE TITLE
མདོ་སྡེ། 最後一函 vol.071目錄顯示應該是 ཨཿ  不是 ཿ

### ISSUE THREAD

**Issue by lamalien** [karmapa/adarsha2014#59]
![32](https://cloud.githubusercontent.com/assets/5266492/5137558/e131c37e-7176-11e4-9921-86739fa03833.jpg)

**Comment by shu-hui** [comment]
香毓;  是 ཨཿ 字

**Comment by lamalien** [comment]
已修正
