### ISSUE TITLE
Kacha can't be expand to text

### ISSUE THREAD

**Issue by lamalien** [karmapa/adarsha2014#6]
![adarsha issue1014-1](https://cloud.githubusercontent.com/assets/5266492/4623343/260918ba-534c-11e4-9a4d-633b4a2688d7.jpg)
![1adarsha](https://cloud.githubusercontent.com/assets/5266492/4623371/f19d1c74-534c-11e4-9e8e-52763240c108.jpg)

**Comment by ahsyuyu** [comment]
顯示文本的地方有做調整，改成一次顯示一個bampo。
目錄裡的1已經改掉了，紅色按鈕也拿掉了。
Thank you for the feedback!

**Comment by lamalien** [comment]
已修正
