### ISSUE TITLE
མདོ་སྡོ། ༼པ༽目錄有漏

### ISSUE THREAD

**Issue by shu-hui** [karmapa/adarsha2014#60]
![5](https://cloud.githubusercontent.com/assets/7776378/5137553/d4ec4d78-7176-11e4-90d1-50d78b66185e.png)

**Comment by shu-hui** [comment]
目錄有漏, 文檔已修訂, 待系統更新後再確認. 謝謝 !!

**Comment by ahsyuyu** [comment]
已經更新資料庫～若確認沒問題再麻煩close此issue了～謝謝！
