### ISSUE TITLE
Kacha expand problem

### ISSUE THREAD

**Issue by lamalien** [karmapa/adarsha2014#8]
![issue2](https://cloud.githubusercontent.com/assets/5266492/4623406/a2801302-534d-11e4-890f-99370917868b.jpg)

**Comment by ahsyuyu** [comment]
點選標題沒有內容的部分已經有修正了，請到目前最新版本v1.0.01操作看是否還有問題。
第二個問題”只有目錄最後一個才可以expand內容“，我不太懂意思，方不方便傳一張截圖說明問題呢？
謝謝！

**Comment by lamalien** [comment]
已修正
