### ISSUE TITLE
目錄標題內多出來的 "་" & 原本內文換行處會產生空格

### ISSUE THREAD

**Issue by lamalien** [karmapa/adarsha2014#93]
![adarsha_issue20141125_1](https://cloud.githubusercontent.com/assets/5266492/5177695/82f997ee-7498-11e4-935e-1310e3d7b5a2.jpg)

**Comment by shu-hui** [comment]
法海師:

內文的空格不是因為每一行的分行，開頭的位置嗎?
若是沒有空格，分行不是就恢復成原本未分行狀態?

**Comment by lamalien** [comment]
已修正
