### ISSUE TITLE
目錄指向錯誤

### ISSUE THREAD

**Issue by padmatara** [karmapa/adarsha2014#99]
![prob 7png](https://cloud.githubusercontent.com/assets/8554534/5179588/6cba02b2-74ba-11e4-9e52-6e12bda54dfd.png)
![prob 8](https://cloud.githubusercontent.com/assets/8554534/5179586/6cb4e110-74ba-11e4-8b9c-eca80024faa0.png)
![prob 9](https://cloud.githubusercontent.com/assets/8554534/5179590/6cbb5694-74ba-11e4-8a72-9011396446be.png)
![prob 10](https://cloud.githubusercontent.com/assets/8554534/5179589/6cba8e62-74ba-11e4-8ab3-7ca8b4813fc4.png)
![prob 11](https://cloud.githubusercontent.com/assets/8554534/5179587/6cb58570-74ba-11e4-86bc-5ab532a0d225.png)
![prob 12](https://cloud.githubusercontent.com/assets/8554534/5179591/6cbb6012-74ba-11e4-8819-82fad3abcd36.png)
![prob 13](https://cloud.githubusercontent.com/assets/8554534/5179593/6cdc6672-74ba-11e4-8f05-96e89213f7f4.png)
![prob 14](https://cloud.githubusercontent.com/assets/8554534/5179595/6cde94ce-74ba-11e4-8e9f-e4347f65bc7b.png)
![prob 1](https://cloud.githubusercontent.com/assets/8554534/5179594/6cddf29e-74ba-11e4-9679-20a476b4f2e2.png)
![prob 2](https://cloud.githubusercontent.com/assets/8554534/5179596/6cdf896a-74ba-11e4-84b7-74727bae3fa4.png)
![prob 3](https://cloud.githubusercontent.com/assets/8554534/5179598/6ce399ce-74ba-11e4-8473-393f6495eaa1.png)
![prob 4](https://cloud.githubusercontent.com/assets/8554534/5179597/6ce1851c-74ba-11e4-9991-dee9fde97257.png)
![prob 5](https://cloud.githubusercontent.com/assets/8554534/5179600/6d06cbba-74ba-11e4-89b0-239525cadd37.png)
![prob 6png](https://cloud.githubusercontent.com/assets/8554534/5179599/6cff9e4e-74ba-11e4-8fc9-151ca0f050fd.png)

**Comment by shu-hui** [comment]
1) 2.48a 已修正
2) 3.121a 尚未修正 (和第4)一樣)
3) 3.102b 已修正
5) 3.130a 已修正
6) 3.166b 已修正
7) 6.137a 尚未修正
8) 6.143a 尚未修正
9) 1.133c 尚未修正 (呈現error)
10) 1.277a 已修正
11) 1.377b 尚未修正 (但煖恩:這應該是1.277b吧)
12)13) 2.1b尚未修正
13) 2.12b 已修正

**Comment by lamalien** [comment]
已改正
